
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class antique : Luban.BeanBase
{
    public antique(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        Verdict = _buf.ReadInt();
        ImageAddress = _buf.ReadString();
        BaseScore = _buf.ReadInt();
        CorrectLine = _buf.ReadString();
        WrongLine = _buf.ReadString();
        UnlockDesc = _buf.ReadString();
    }

    public static antique Deserializeantique(ByteBuf _buf)
    {
        return new antique(_buf);
    }

    /// <summary>
    /// 藏品ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 藏品名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 展示描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 正确分类(1真2假3特殊)
    /// </summary>
    public readonly int Verdict;
    /// <summary>
    /// 图片YooAsset地址
    /// </summary>
    public readonly string ImageAddress;
    /// <summary>
    /// 基础分
    /// </summary>
    public readonly int BaseScore;
    /// <summary>
    /// 判对吐槽
    /// </summary>
    public readonly string CorrectLine;
    /// <summary>
    /// 判错吐槽
    /// </summary>
    public readonly string WrongLine;
    /// <summary>
    /// 图鉴描述
    /// </summary>
    public readonly string UnlockDesc;
   
    public const int __ID__ = -846880737;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "verdict:" + Verdict + ","
        + "imageAddress:" + ImageAddress + ","
        + "baseScore:" + BaseScore + ","
        + "correctLine:" + CorrectLine + ","
        + "wrongLine:" + WrongLine + ","
        + "unlockDesc:" + UnlockDesc + ","
        + "}";
    }
}
}

