
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class bossLine : Luban.BeanBase
{
    public bossLine(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        TriggerType = _buf.ReadInt();
        MinCombo = _buf.ReadInt();
        Line = _buf.ReadString();
        AudioAddress = _buf.ReadString();
    }

    public static bossLine DeserializebossLine(ByteBuf _buf)
    {
        return new bossLine(_buf);
    }

    /// <summary>
    /// 吐槽ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡id(0全局)
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 触发类型
    /// </summary>
    public readonly int TriggerType;
    /// <summary>
    /// 最低连击
    /// </summary>
    public readonly int MinCombo;
    /// <summary>
    /// 吐槽文本
    /// </summary>
    public readonly string Line;
    /// <summary>
    /// 语音资源地址
    /// </summary>
    public readonly string AudioAddress;
   
    public const int __ID__ = 2126307585;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "triggerType:" + TriggerType + ","
        + "minCombo:" + MinCombo + ","
        + "line:" + Line + ","
        + "audioAddress:" + AudioAddress + ","
        + "}";
    }
}
}

