
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class gameRule : Luban.BeanBase
{
    public gameRule(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ComboNeed = _buf.ReadInt();
        ComboMultiplier = _buf.ReadInt();
        WrongReputationCost = _buf.ReadInt();
        FeedbackDurationMs = _buf.ReadInt();
    }

    public static gameRule DeserializegameRule(ByteBuf _buf)
    {
        return new gameRule(_buf);
    }

    /// <summary>
    /// 规则ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 达到该倍率所需连击
    /// </summary>
    public readonly int ComboNeed;
    /// <summary>
    /// 得分倍率
    /// </summary>
    public readonly int ComboMultiplier;
    /// <summary>
    /// 判错信誉扣除
    /// </summary>
    public readonly int WrongReputationCost;
    /// <summary>
    /// 判定反馈停留毫秒
    /// </summary>
    public readonly int FeedbackDurationMs;
   
    public const int __ID__ = -1769206258;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "comboNeed:" + ComboNeed + ","
        + "comboMultiplier:" + ComboMultiplier + ","
        + "wrongReputationCost:" + WrongReputationCost + ","
        + "feedbackDurationMs:" + FeedbackDurationMs + ","
        + "}";
    }
}
}

