
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class levelAntique : Luban.BeanBase
{
    public levelAntique(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        LevelId = _buf.ReadInt();
        AntiqueId = _buf.ReadInt();
        SpawnOrder = _buf.ReadInt();
        IsRequired = _buf.ReadBool();
    }

    public static levelAntique DeserializelevelAntique(ByteBuf _buf)
    {
        return new levelAntique(_buf);
    }

    /// <summary>
    /// 唯一id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡id
    /// </summary>
    public readonly int LevelId;
    /// <summary>
    /// 藏品ID
    /// </summary>
    public readonly int AntiqueId;
    /// <summary>
    /// 出货顺序
    /// </summary>
    public readonly int SpawnOrder;
    /// <summary>
    /// 是否必出
    /// </summary>
    public readonly bool IsRequired;
   
    public const int __ID__ = 432234491;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "levelId:" + LevelId + ","
        + "antiqueId:" + AntiqueId + ","
        + "spawnOrder:" + SpawnOrder + ","
        + "isRequired:" + IsRequired + ","
        + "}";
    }
}
}

