
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class level : Luban.BeanBase
{
    public level(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        DurationSeconds = _buf.ReadInt();
        InitialReputation = _buf.ReadInt();
        TargetScore = _buf.ReadInt();
        PassScore = _buf.ReadInt();
        UnlockLevelId = _buf.ReadInt();
    }

    public static level Deserializelevel(ByteBuf _buf)
    {
        return new level(_buf);
    }

    /// <summary>
    /// 关卡ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 关卡名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 主题描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 限时秒数
    /// </summary>
    public readonly int DurationSeconds;
    /// <summary>
    /// 初始信誉
    /// </summary>
    public readonly int InitialReputation;
    /// <summary>
    /// 目标分
    /// </summary>
    public readonly int TargetScore;
    /// <summary>
    /// 过关分
    /// </summary>
    public readonly int PassScore;
    /// <summary>
    /// 解锁的下一关ID
    /// </summary>
    public readonly int UnlockLevelId;
   
    public const int __ID__ = 102865796;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "durationSeconds:" + DurationSeconds + ","
        + "initialReputation:" + InitialReputation + ","
        + "targetScore:" + TargetScore + ","
        + "passScore:" + PassScore + ","
        + "unlockLevelId:" + UnlockLevelId + ","
        + "}";
    }
}
}

