
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class Tbantique
{
    private readonly System.Collections.Generic.Dictionary<int, antique> _dataMap;
    private readonly System.Collections.Generic.List<antique> _dataList;
    
    public Tbantique(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, antique>(n);
        _dataList = new System.Collections.Generic.List<antique>(n);
        for(int i = n ; i > 0 ; --i)
        {
            antique _v;
            _v = global::GameConfig.antique.Deserializeantique(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, antique> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<antique> DataList => _dataList;

    public antique GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public antique Get(int key) => _dataMap[key];
    public antique this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

