
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbbossLine
{
    private readonly System.Collections.Generic.Dictionary<int, bossLine> _dataMap;
    private readonly System.Collections.Generic.List<bossLine> _dataList;
    
    public TbbossLine(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, bossLine>(n);
        _dataList = new System.Collections.Generic.List<bossLine>(n);
        for(int i = n ; i > 0 ; --i)
        {
            bossLine _v;
            _v = global::GameConfig.bossLine.DeserializebossLine(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, bossLine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<bossLine> DataList => _dataList;

    public bossLine GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public bossLine Get(int key) => _dataMap[key];
    public bossLine this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

