
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbgameRule
{
    private readonly System.Collections.Generic.Dictionary<int, gameRule> _dataMap;
    private readonly System.Collections.Generic.List<gameRule> _dataList;
    
    public TbgameRule(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, gameRule>(n);
        _dataList = new System.Collections.Generic.List<gameRule>(n);
        for(int i = n ; i > 0 ; --i)
        {
            gameRule _v;
            _v = global::GameConfig.gameRule.DeserializegameRule(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, gameRule> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<gameRule> DataList => _dataList;

    public gameRule GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public gameRule Get(int key) => _dataMap[key];
    public gameRule this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

