
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TblevelAntique
{
    private readonly System.Collections.Generic.Dictionary<int, levelAntique> _dataMap;
    private readonly System.Collections.Generic.List<levelAntique> _dataList;
    
    public TblevelAntique(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, levelAntique>(n);
        _dataList = new System.Collections.Generic.List<levelAntique>(n);
        for(int i = n ; i > 0 ; --i)
        {
            levelAntique _v;
            _v = global::GameConfig.levelAntique.DeserializelevelAntique(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, levelAntique> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<levelAntique> DataList => _dataList;

    public levelAntique GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public levelAntique Get(int key) => _dataMap[key];
    public levelAntique this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

