
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class Tblevel
{
    private readonly System.Collections.Generic.Dictionary<int, level> _dataMap;
    private readonly System.Collections.Generic.List<level> _dataList;
    
    public Tblevel(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, level>(n);
        _dataList = new System.Collections.Generic.List<level>(n);
        for(int i = n ; i > 0 ; --i)
        {
            level _v;
            _v = global::GameConfig.level.Deserializelevel(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, level> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<level> DataList => _dataList;

    public level GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public level Get(int key) => _dataMap[key];
    public level this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

