
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public partial class TbmyTestTable
{
    private readonly System.Collections.Generic.Dictionary<int, myTestTable> _dataMap;
    private readonly System.Collections.Generic.List<myTestTable> _dataList;
    
    public TbmyTestTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, myTestTable>(n);
        _dataList = new System.Collections.Generic.List<myTestTable>(n);
        for(int i = n ; i > 0 ; --i)
        {
            myTestTable _v;
            _v = global::GameConfig.myTestTable.DeserializemyTestTable(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, myTestTable> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<myTestTable> DataList => _dataList;

    public myTestTable GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public myTestTable Get(int key) => _dataMap[key];
    public myTestTable this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

